<?xml version="1.0" encoding="ISO-8859-1"?>
<im:InstantMessagingClient xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:im="platform:/resource/uml1cs-instantmessenger-model/metamodels/InstantMessengerFeatures.ecore"
    xmlns:refinements="platform:/resource/uml1cs-transformations/metamodels/Refinements.ecore">
  <network xsi:type="im:Jabber">
    <transport xsi:type="im:MEJabber"/>
  </network>
  <network xsi:type="im:Local"/>
  <network xsi:type="im:SMS"/>
  <userInterface xsi:type="im:LCDUI"/>
  <refinementConfiguration>
    <first xsi:type="refinements:AssociationAttributes">
      <next xsi:type="refinements:Accessors">
        <next xsi:type="refinements:Observer">
          <next>
            <next xsi:type="refinements:MIDlet">
              <next>
                <next xsi:type="refinements:DataTypes">
                  <next xsi:type="refinements:UMLtoJava"/>
                </next>
              </next>
            </next>
          </next>
        </next>
      </next>
    </first>
  </refinementConfiguration>
</im:InstantMessagingClient>
