<?xml version="1.0" encoding="ISO-8859-1"?>
<im:InstantMessagingClient xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:im="platform:/resource/uml1cs-instantmessenger-model/metamodels/InstantMessengerFeatures.ecore"/>
