<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="im"
    nsURI="platform:/resource/uml1cs-instantmessenger-model/metamodels/InstantMessengerFeatures.ecore"
    nsPrefix="im">
  <eClassifiers xsi:type="ecore:EClass" name="InstantMessagingClient">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#InstantMessagingClientPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        upperBound="-1" eType="#//Network" containment="true" eOpposite="#//Network/client"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInterface" lowerBound="1"
        upperBound="-1" eType="#//UserInterface" containment="true" eOpposite="#//UserInterface/client"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinementConfiguration"
        lowerBound="1" eType="ecore:EClass ../../uml1cs-transformations/metamodels/Refinements.ecore#//RefinementConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packaging" lowerBound="1"
        eType="#//Packaging" containment="true" eOpposite="#//Packaging/client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Jabber" eSuperTypes="#//Network">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#JabberPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" lowerBound="1"
        eType="#//JabberTransport" containment="true" eOpposite="#//JabberTransport/jabber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultJabber" eSuperTypes="#//JabberTransport">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#DefaultJabberPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEJabber" eSuperTypes="#//JabberTransport">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#MEJabberPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMS" eSuperTypes="#//Network">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#SMSPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Local" eSuperTypes="#//Network">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#LocalPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swing" eSuperTypes="#//UserInterface">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#SwingPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AWT" eSuperTypes="#//UserInterface">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#AWTPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LCDUI" eSuperTypes="#//UserInterface">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#LCDUIPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//InstantMessagingClient" eOpposite="#//InstantMessagingClient/network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JabberTransport" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jabber" lowerBound="1"
        eType="#//Jabber" defaultValueLiteral="" eOpposite="#//Jabber/transport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//InstantMessagingClient" eOpposite="#//InstantMessagingClient/userInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packaging" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//InstantMessagingClient" eOpposite="#//InstantMessagingClient/packaging"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebApplet" eSuperTypes="#//Packaging">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#WebAppletPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ipkg" eSuperTypes="#//Packaging">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#IpkgPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIDletJar" eSuperTypes="#//Packaging">
    <eAnnotations source="http://local/InstantMessengerConstraints.owl#MIDletPlatform"
        references="../../uml1cs-transformations/metamodels/Refinements.ecore#//ContextConstraint"/>
  </eClassifiers>
</ecore:EPackage>
